WIP JAMES-XXXX ADR for Mailbox/changes
linagora/james-project pull request #4112
Opened 2020-12-07 11:23 UTC by LanKhuat

2020-12-07 12:02 UTC, chibenwa requested changes
THE most important comment: ADR should be opened against Apache repository...

2020-12-07 12:02 UTC, chibenwa commented on src/adr/0044-mailbox-changes.md
> +ORDERED BY date
ORDERED BY STATE, state being a timeuuid

You cannot order things by a column, only by the first clustering key.

2020-12-07 12:02 UTC, chibenwa commented on src/adr/0044-mailbox-changes.md
> +COLUMN state
state should be a clustering column

2020-12-07 16:34 UTC, rouazana reviewed
can we have a word about concurrency?
I mean: what happens when 2 changes occur at the same time? how do you ensure there is no conflicting change?

2020-12-08 03:06 UTC, LanKhuat commented on src/adr/0044-mailbox-changes.md
> +COLUMN isMailboxChange
for this: https://issues.apache.org/jira/browse/JAMES-3465 ?

2020-12-08 03:08 UTC, LanKhuat commented on src/adr/0044-mailbox-changes.md
> +However, by keeping the data type of changes as separeted lists, we will be more open for future improvements.
it is still a part of the first bullet point with a line break?

2020-12-08 03:37 UTC, chibenwa commented on src/adr/0044-mailbox-changes.md
> +COLUMN isMailboxChange
I then suggest `COLUMN isCountChange`

2020-12-08 04:12 UTC, chibenwa reviewed
We do miss the links to the JIRAs too?

Open this against the Apache repository!

2020-12-08 04:48 UTC, LanKhuat commented
https://github.com/apache/james-project/pull/276

2020-12-08 04:48 UTC, closed without merging